version: '3'
services:
  app:
    image: librairy-training-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ikram2003@
      POSTGRES_DB: gestion_vols
    ports:
      - "5432:5432"
